name: 3D-Contribution-Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: randirao

      - name: Commit images
        run: |
          mkdir -p profile-3d-contrib
          cp -r out/* profile-3d-contrib/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib || true
          git commit -m "chore: update 3D contrib" || echo "no changes"
          git push
